### PR TITLE
[DCGAN] Add support for FID metric

### PR DESCRIPTION
**Pull request by NielsRogge**
This PR adds support for the FID metric when training DCGAN.

### CODE REVIEW

**Comment by osanseviero** [comment]
Very nice! :rocket:

**Comment by NielsRogge** [comment]
I'd like to make this metric usable by all PyTorch models.

I tried to define it in a separate "metrics" folder, but then I get:

```
from ..metrics.inception import InceptionV3
ImportError: attempted relative import with no known parent package
```

**Comment by osanseviero** [comment]
I think you need to do `from huggan.metrics.inception import InceptionV3` or add a `__init__.py` at metrics.

**Comment by NielsRogge** [comment]
Maybe @nateraw can help here. Maybe the "metrics" should be a folder alongside "dcgan", "pix2pix" etc., since the metrics are PyTorch-specific (it uses a pre-trained PyTorch model).

**Comment by nateraw** [comment]
I will take a shot at this one today @NielsRogge ! 😄

**Comment by FrancescoSaverioZuppichini** [comment]
Another fix is to define a `train` function for each of the models and create a script at **top root** (e.g. `train.py`) that calls it and passes the right parameters (I think all the parameters are more or less the same for all models). Cleaner but probably we prefer to encapsulate everything inside each mode folder

**Comment by osanseviero** [comment]
I think 2 would be fine. Pretty much this requires

1. Adding an `__init__.py` to all directories
2. Change imports to be absolute, e.g. `from huggan.pytorch.dcgan.modeling_dcgan import Discriminator, Generator`
3. Add a `setup.py` file with something like

```
from setuptools import setup, find_packages  
setup(name = 'huggan', packages = find_packages())
```

4. Ask users to do `python huggan/setup.py install` which is not much tbh. We could even add the dependencies here since they will be needed anyways.

**Pull request merged**
