### PR TITLE
[WIP] add wandb team

### PR DESCRIPTION
**Pull request by yiyixuxu**
updated the training script so that people can log the training to their team account 
also want to use this PR to update the instructions on how to create free wandb team account (waiting for inputs from wandb team)

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
Good idea to just keep the wandb entity flag here. 

For forming teams on WandB, I think we just link the official documentation, no?

https://docs.wandb.ai/guides/app/features/teams

**Comment by yiyixuxu** [comment]
I thought we need to go through a process to apply for a free account or something, otherwise it's not free no? @sayakpaul

**Comment by yiyixuxu** [comment]
@sayakpaul oh I added the entity flag on diffuser repo too, default it's None so it will just log to your personal account.

**Review by soumik12345 — COMMENTED** [review]
Hi, @yiyixuxu It would be great if you could add this link https://wandb.ai/subscriptions to the readme along with the docs link suggested by @sayakpaul. This is where a user can manage the storage for their teams.

**Comment by sayakpaul** [comment]
Sounds good! @yiyixuxu over to you.

**Comment by soumik12345** [comment]
@yiyixuxu Sounds great.

**Pull request merged**
