### PR TITLE
[DCGAN] Make script work on multiple GPUs

### PR DESCRIPTION
**Pull request by NielsRogge**
I wanted to run the script using Accelerate, so I did the steps explained in the docs:

`accelerate config
`
then

`accelerate launch train.py`

however, it only seems to use a single GPU, even though 2 are available.

cc'ing @sgugger

### CODE REVIEW

**Comment by sgugger** [comment]
`- num_processes: 1` -> so it's using only one GPU because that's what you asked for.

**Comment by NielsRogge** [comment]
Setting `num_processes` to 2 gives me this:

```
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/niels/.pyenv/versions/3.9.10/bin/python3.9: can't open file '/home/niels/python_projects/community-events-1/train.py': [Errno 2] No such file or directory
/home/niels/.pyenv/versions/3.9.10/bin/python3.9: can't open file '/home/niels/python_projects/community-events-1/train.py': [Errno 2] No such file or directory
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 23525) of binary: /home/niels/.pyenv/versions/3.9.10/bin/python3.9
Traceback (most recent call last):
  File "/home/niels/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/niels/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/niels/.pyenv/versions/3.9.10/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/niels/.pyenv/versions/3.9.10/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/niels/.pyenv/versions/3.9.10/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/niels/.pyenv/versions/3.9.10/lib/python3.9/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/niels/.pyenv/versions/3.9.10/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/niels/.pyenv/versions/3.9.10/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-03-24_14:36:49
  host      : brutasse
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 23526)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-03-24_14:36:49
  host      : brutasse
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 23525)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home/niels/.pyenv/versions/3.9.10/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/niels/.pyenv/versions/3.9.10/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/niels/.pyenv/versions/3.9.10/lib/python3.9/site-packages/accelerate/commands/launch.py", line 469, in launch_command
    multi_gpu_launcher(args)
  File "/home/niels/.pyenv/versions/3.9.10/lib/python3.9/site-packages/accelerate/commands/launch.py", line 229, in multi_gpu_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/niels/.pyenv/versions/3.9.10/bin/python3.9', '-m', 'torch.distributed.launch', '--use_env', '--nproc_per_node', '2', 'train.py']' returned non-zero exit status 1.
```

**Comment by sgugger** [comment]
It seems you are trying to execute a training script that does not exists:
```
/home/niels/.pyenv/versions/3.9.10/bin/python3.9: can't open file '/home/niels/python_projects/community-events-1/train.py': [Errno 2] No such file or directory
```

**Comment by NielsRogge** [comment]
Ok it works, sorry that error looked very cryptic but I was indeed running it from the wrong directory.

**Pull request merged**
