### PR TITLE
Fix directory for keras notebook

### PR DESCRIPTION
**Pull request by merveenoyan**
This PR fixes directory of MNIST notebook

### CODE REVIEW

**Review by osanseviero — CHANGES_REQUESTED** [review]
We should also delete https://github.com/huggingface/community-events/tree/main/examples/vision/ipynb

**Comment by merveenoyan** [comment]
@osanseviero I did though and I did `git add .` so I don't know why it doesn't remove 😂

**Comment by merveenoyan** [comment]
ok apparently it should be git rm lol

**Review by osanseviero — APPROVED** [review]
LG! Could you please also confirm the directory examples is deleted? (I think this PR is leaving an empty directory right now)

**Comment by merveenoyan** [comment]
```
(base) ➜  community-events git:(fix_dir) ls
README.md        huggan           requirements.txt
gradio-blocks    keras-sprint     setup.py
```

**Comment by merveenoyan** [comment]
Ekran Resmi 2022-06-06 18 23 21

**Pull request merged**
